{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
data:
  redisPassword: {{ .Values.redis.secretPassword | b64enc | quote }}
{{- end -}}