apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.fullname" . }}-secret
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
data:
  httpSecret: {{ randAlphaNum 12 | b64enc | quote }}
  htpasswd: {{ .Values.secrets.htpasswd | b64enc | quote }}
{{- if eq .Values.storage.type "s3" }}
  s3AccessKey: {{ required "access key needs to be defined" .Values.storage.s3.s3AccessKey | b64enc | quote }}
  s3SecretKey: {{ required "key secret needs to be defined" .Values.storage.s3.s3SecretKey | b64enc | quote }}
{{- end -}}